### ISSUE TITLE
AssertionError: 80

### ISSUE THREAD

**Issue by thejumboroar** [thejumboroar/kinect-v2-livestream#1]
> Traceback (most recent call last):
> 
>   File "C:\networks\kinect-v2-livestream\kinect_v2_livestream.py", line 1, in <module>
>     from pykinect2 import PyKinectV2
> 
>   File "C:\libs\Anaconda3\envs\Deephar\lib\site-packages\pykinect2\PyKinectV2.py", line 2216, in <module>
>     assert sizeof(tagSTATSTG) == 72, sizeof(tagSTATSTG)
> 
> AssertionError: 80

**Comment by thejumboroar** [comment]
Go to the pykinect2 installation in the site-packages folder (Lib\site-packages\pykinect2) and replace the .py files with the ones from the [github repository](https://github.com/Kinect/PyKinect2/tree/master/pykinect2).
